spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root221899
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
